UseHover/Stax

.idea/gradle.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/hover/stax/database/Constants.java
app/src/main/java/com/hover/stax/requests/RequestActivity.java
app/src/main/java/com/hover/stax/requests/SmsReceiver.java
app/src/main/java/com/hover/stax/requests/SmsSentObserver.java
app/src/main/java/com/hover/stax/utils/PermissionUtils.java
app/src/main/res/values/logging_strings.xml
app/src/main/res/values/strings.xml

Updates to use more universal SMS intent api and an SMS observer to detect when SMS are actually sent.

175192569 smsfixes

---

app/src/main/java/com/hover/stax/requests/EditRequestFragment.java
app/src/main/java/com/hover/stax/requests/NewRequestFragment.java
app/src/main/java/com/hover/stax/requests/NewRequestViewModel.java
app/src/main/java/com/hover/stax/requests/RecipientAdapter.java
app/src/main/java/com/hover/stax/requests/RequestActivity.java
app/src/main/java/com/hover/stax/requests/RequestDetailFragment.java
app/src/main/java/com/hover/stax/schedules/ScheduleDetailFragment.java
app/src/main/java/com/hover/stax/utils/StagedFragment.java
app/src/main/java/com/hover/stax/utils/StagedViewModel.java
app/src/main/res/layout/activity_request.xml
app/src/main/res/layout/fragment_edit_request.xml
app/src/main/res/layout/repeat_inputs.xml
app/src/main/res/layout/request_card_edit.xml
app/src/main/res/layout/request_card_summary.xml
app/src/main/res/layout/transfer_card_repeat.xml
app/src/main/res/navigation/request_navigation.xml
app/src/main/res/values/strings.xml

Adds an edit button to change input values after the first field is filled in on Transfer, buy airtime, or request money. Sends user to a new fragment which holds all inputs in a single card. The detailed functionality is described in the pivotal story.
[Finishes #175204884}

175204884 edittransfers

---

.idea/gradle.xml
app/src/main/java/com/hover/stax/channels/Channel.java
app/src/main/java/com/hover/stax/channels/ChannelDetailFragment.java
app/src/main/java/com/hover/stax/channels/ChannelListFragment.java
app/src/main/java/com/hover/stax/channels/ChannelListViewModel.java
app/src/main/java/com/hover/stax/channels/ChannelsActivity.java
app/src/main/java/com/hover/stax/transfers/TransferActivity.java
app/src/main/java/com/hover/stax/utils/customSwipeRefresh/CustomSwipeRefreshLayout.java

A couple of things needs optimisation.
1. The SplashScreenForStaxLinkActivity - I had to use this because the same Splash screen activity as the launcher wasn't working for the app link intent filter. 
2. EncryptionSettings in the DatabaseRepo. We might need to store those settings somewhere in the server and cache it locally alongside actions or elsewhere. So that the same settings can be used for online payments. Just my thoughts, please share other approaches to this.

175377597 payment links

---

app/src/main/java/com/hover/stax/database/AppDatabase.java
app/src/main/java/com/hover/stax/database/SdkDatabase.java

1. Checked out from the development branch.

added migration snippets with jornal mode non-destructive

---

.idea/gradle.xml
app/build.gradle
app/src/main/java/com/hover/stax/bounties/Bounty.java
app/src/main/java/com/hover/stax/bounties/BountyListFragment.java
app/src/main/java/com/hover/stax/bounties/BountyViewModel.java
app/src/main/java/com/hover/stax/database/DatabaseRepo.java
app/src/main/res/layout/stax_dialog.xml
app/src/main/res/values/strings.xml

- Updated sdk to call: getPresentByHnis(String[] hnis). It was a minor addition so I just added it as a push commit to stax branch. Deployed a release 1.7.2-stax-1.2.1, which also fixes the SMS parser issue for release version
-Recent designs colors button for positive dialog btn, updated codebase to reflect this.
- No sim state

177461250 bounty no sim state

---

app/src/main/java/com/hover/stax/bounties/BountyViewModel.java
app/src/main/java/com/hover/stax/countries/CountryAdapter.java
app/src/main/java/com/hover/stax/countries/CountryDropdown.java
app/src/main/res/values/strings.xml

Added all countries item to bounty's list of country filter

[finishes #177627607] story completed

---

app/src/main/java/com/hover/stax/transactions/TransactionDetailsFragment.java
app/src/main/res/layout/bounty_retry_submit_btn_layout.xml

Remove submit  bounty button from transaction details page

[finishes #177635576] story completed

---

.idea/gradle.xml
app/src/main/java/com/hover/stax/bounties/BountyListFragment.java
app/src/main/java/com/hover/stax/channels/ChannelDropdown.java
app/src/main/java/com/hover/stax/settings/SettingsFragment.java
app/src/main/res/drawable/ic_baseline_open_in_new_24.xml
app/src/main/res/layout/contact_stax_layout.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values/strings.xml

177630576 addtwitter contact

---

app/build.gradle
app/src/main/java/com/hover/stax/SplashScreenActivity.java
app/src/main/java/com/hover/stax/destruct/SelfDestructActivity.java

- Sets `keystore properties` in local environment for local builds. 
- Allows Android Studio to handle signing of apks/bundles on our behalf.

Sets up automatic signing from Android Studio

---

app/src/main/java/com/hover/stax/bounties/BountyActivity.java
app/src/main/java/com/hover/stax/navigation/AbstractNavigationActivity.java
app/src/main/res/navigation/bounty_navigation.xml

fix back navigation from bounty list fragment to settings fragment.

navigation fix

---

.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/compiler.xml
.idea/misc.xml
app/build.gradle
app/src/main/java/com/hover/stax/bounties/BountyActivity.java
app/src/main/java/com/hover/stax/navigation/AbstractNavigationActivity.java
app/src/main/res/drawable/selector_icon_tint.xml
app/src/main/res/layout/fragment_channel.xml
app/src/main/res/layout/request_card_summary.xml
app/src/main/res/layout/request_detail_card_summary.xml
app/src/main/res/menu/nav_main.xml
app/src/main/res/navigation/bounty_navigation.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

- adds missing back navigation button on account detail, new request detail and transaction details screens.

minor fixes

---

.idea/jarRepositories.xml
.idea/misc.xml
app/build.gradle
app/proguard-rules.pro
app/src/main/AndroidManifest.xml
app/src/main/java/com/hover/stax/ApplicationInstance.java
app/src/main/java/com/hover/stax/SplashScreenActivity.java
app/src/main/java/com/hover/stax/bounties/BountyActivity.java
app/src/main/java/com/hover/stax/languages/SelectLanguageActivity.java
app/src/main/res/values/strings.xml
build.gradle

Completed setting up appsflyter.
P.S, I added the snippet below to Bounty and Language activity to ensure AppsFlyer starts even when a user comes into the app via deep link without passing through Splashscreen.
@Override
protected void onStart() {
super.onStart();
AppsFlyerLib.getInstance().start(this);
}

178037988 add appsflyer

---

app/build.gradle
app/src/main/java/com/hover/stax/SplashScreenActivity.java
app/src/main/java/com/hover/stax/actions/ActionDropdownAdapter.java
app/src/main/java/com/hover/stax/actions/ActionSelect.java
app/src/main/java/com/hover/stax/balances/BalancesFragment.java
app/src/main/java/com/hover/stax/balances/BalancesViewModel.java
app/src/main/java/com/hover/stax/bounties/BountyEmailFragment.java
app/src/main/java/com/hover/stax/channels/ChannelDropdownAdapter.java
app/src/main/java/com/hover/stax/home/MainActivity.java
app/src/main/java/com/hover/stax/permissions/PermissionsFragment.java
app/src/main/java/com/hover/stax/requests/RequestSenderInterface.java
app/src/main/java/com/hover/stax/settings/PinsViewModel.java
app/src/main/res/layout/balance_item.xml

Revert "Bugfixes"

---

app/src/main/java/com/hover/stax/bounties/BountyActivity.java
app/src/main/java/com/hover/stax/bounties/BountyEmailFragment.java
app/src/main/java/com/hover/stax/bounties/BountyListFragment.java
app/src/main/java/com/hover/stax/utils/Utils.java
app/src/main/java/com/hover/stax/views/StaxDialog.java
app/src/main/res/values/strings.xml

Forcing user to be online in other to do Bounties
Set logic to onResume so it cover edge cases when Stax is in the background and user comes back to it.

178131446 online bounty page

---

app/build.gradle
app/src/main/java/com/hover/stax/channels/ChannelsListFragment.java
app/src/main/java/com/hover/stax/transactions/StaxTransaction.java
app/src/main/res/values/strings.xml

- ask for permissions before the account list 
- add an error message to tell the user to go online if the channel list hasn't downloaded yet
- add a dialog that says check balance.

bug fixes and alignment with the latest design

---

app/src/main/java/com/hover/stax/home/MainActivity.java
app/src/main/java/com/hover/stax/navigation/AbstractNavigationActivity.java
app/src/main/java/com/hover/stax/requests/NewRequestFragment.java

Fix for: Back from send money or request always leaves Get paid highlighted

178520182 get paid navigation bugfixes

---

app/src/main/java/com/hover/stax/hover/HoverSession.java
app/src/main/java/com/hover/stax/settings/SettingsFragment.java
app/src/main/java/com/hover/stax/utils/Constants.kt
app/src/main/java/com/hover/stax/utils/Utils.kt
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/support_card_layout.xml
app/src/main/res/values/strings.xml

Added support for test mode by tapping disclaimer in settings

---

app/src/main/res/layout/slide2_fragment.xml
app/src/main/res/layout/slide3_fragment.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml

Updated onboarding copy: https://www.notion.so/usehover/Copy-for-Onboarding-Screen-93c75145b14b4b8ebb549bb4bce69a07

178931651 onboarding copy

---

app/src/main/java/com/hover/stax/faq/FaqFragment.kt
app/src/main/res/values/strings.xml

Showing device id is made optional in this scenario when user goes through faq

completed story for: Add device id to  CTA under the In-app FAQs

---

app/src/main/java/com/hover/stax/inapp_banner/Banner.kt
app/src/main/java/com/hover/stax/settings/SettingsFragment.java
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/stayintouch_stax_layout.xml
app/src/main/res/values/strings.xml

: On in-app banner logic.... When user clicks, we can make the impression NOT cancel, if it has 2 or more impressions running, if it has 0 or 1 impressions left, it adds 1 more impression.

178930867 setting page subcribe email

---

app/src/main/java/com/hover/stax/bounties/Bounty.java
app/src/main/java/com/hover/stax/bounties/BountyListItem.java
app/src/main/res/drawable/ic_cancel_red.xml
app/src/main/res/drawable/ic_cancel_yellow.xml
app/src/main/res/values/strings.xml

- Because this bug is p0 to product. This branch has been merged to QA branch for functional QA, hence PR to this branch for code QA.
- Failed state was not factored in the bounty transaction initially, this addition fixes that.

179183459 bounty failed state

---

app/src/main/java/com/hover/stax/channels/ChannelDetailViewModel.kt
app/src/main/java/com/hover/stax/database/DatabaseRepo.kt
app/src/main/java/com/hover/stax/transactions/TransactionDao.kt

make transacton history in an account show all transactions including the failed ones

---

.idea/misc.xml
app/src/main/java/com/hover/stax/bounties/BountyActivity.kt
app/src/main/java/com/hover/stax/channels/ChannelsViewModel.kt
app/src/main/java/com/hover/stax/home/MainActivity.kt
app/src/main/java/com/hover/stax/permissions/PermissionUtils.java
app/src/main/java/com/hover/stax/settings/LoginDialog.kt
app/src/main/java/com/hover/stax/settings/LoginNetworking.kt
app/src/main/java/com/hover/stax/settings/ReferralDialog.kt
app/src/main/java/com/hover/stax/settings/SettingsFragment.kt
app/src/main/java/com/hover/stax/settings/SettingsViewModel.kt
app/src/main/java/com/hover/stax/views/StaxDialog.java
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/settings_card_share.xml
app/src/main/res/layout/stax_referral_dialog.xml
app/src/main/res/values/logging_strings.xml
app/src/main/res/values/strings.xml

https://www.loom.com/share/7d41c4a928194c5e827889b9cfe73d60
Moves referrals to its own dialog and forces sign in first. Updates server calls and includes google token, tho that is not yet checked on the backend.

179922098 referrals

---

app/build.gradle
app/src/main/java/com/hover/stax/financialTip/FinancialTipsViewModel.kt
app/src/main/java/com/hover/stax/utils/DateUtils.kt

- Adds sorting for financial tips.

adds sorting for financial tips

---

.idea/misc.xml
app/src/main/java/com/hover/stax/bounties/Bounty.kt
app/src/main/java/com/hover/stax/home/MainActivity.kt
app/src/main/res/layout/stax_transacting_in_progress.xml
app/src/main/res/values/strings.xml

Fix for using some of the SDK's android variables. Requires https://github.com/UseHover/hover-sdk/pull/64

Add support for bounties that are cross border

---

app/src/main/java/com/hover/stax/channels/ChannelDao.kt
app/src/main/java/com/hover/stax/channels/ChannelUtil.kt
app/src/main/java/com/hover/stax/channels/ImportChannelsWorker.kt
app/src/main/java/com/hover/stax/channels/UpdateChannelsWorker.kt

- removes all channels before updating the list on the workers
- changes the update channels worker to a coroutineworker

Channels Update

---

app/src/main/java/com/hover/stax/financialTips/FinancialTipsFragment.kt
app/src/main/java/com/hover/stax/home/HomeFragment.kt
app/src/main/res/layout/card_wellness_tips.xml
app/src/main/res/navigation/home_navigation.xml

- adds different touch points for wellness tips cta.
- fixes navigation bug for duplicated wellness fragments

Financial tips CTA

---

app/build.gradle
app/src/main/java/com/hover/stax/RoutingActivity.kt
app/src/main/java/com/hover/stax/channels/AddChannelsFragment.kt
app/src/main/java/com/hover/stax/channels/ChannelsViewModel.kt
app/src/main/java/com/hover/stax/home/HomeFragment.kt
app/src/main/java/com/hover/stax/onboarding/OnBoardingActivity.kt
app/src/main/res/layout/fragment_home.xml
app/src/main/res/navigation/home_navigation.xml
app/src/main/res/xml/remote_config_default.xml

- channel imports only happen if no channels detected hence import notification won't always show up on app start
- updates MVT tags to new experiment

Minor updates

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/hover/stax/accounts/AccountDao.kt
app/src/main/java/com/hover/stax/accounts/AccountDetailFragment.kt
app/src/main/java/com/hover/stax/accounts/AccountDropdown.kt
app/src/main/java/com/hover/stax/accounts/AccountsFragment.kt
app/src/main/java/com/hover/stax/actions/ActionSelectViewModel.kt
app/src/main/java/com/hover/stax/balances/BalancesFragment.kt
app/src/main/java/com/hover/stax/balances/BalancesViewModel.kt
app/src/main/java/com/hover/stax/channels/ChannelsViewModel.kt
app/src/main/java/com/hover/stax/channels/UpdateChannelsWorker.kt
app/src/main/java/com/hover/stax/database/DatabaseRepo.kt
app/src/main/java/com/hover/stax/home/StaxNavigation.kt
app/src/main/java/com/hover/stax/hover/TransactionReceiver.kt
app/src/main/java/com/hover/stax/requests/NewRequestFragment.kt
app/src/main/java/com/hover/stax/requests/NewRequestViewModel.kt
app/src/main/java/com/hover/stax/transfers/AbstractFormFragment.kt
app/src/main/java/com/hover/stax/transfers/TransferFragment.kt
app/src/main/java/com/hover/stax/utils/Constants.kt
app/src/main/java/com/hover/stax/views/StaxCardView.kt
app/src/main/res/layout/fragment_signin_variant.xml
app/src/main/res/values/strings.xml
build.gradle

- Account placeholders added if user chooses to check balance later. 
- Adds prompts for users to complete account setup if not done. 
- Adds validation to ensure only valid accounts are used.

180603546 bugfix accounts

---

app/src/main/java/com/hover/stax/accounts/Account.kt
app/src/main/java/com/hover/stax/accounts/AccountDao.kt
app/src/main/java/com/hover/stax/balances/BalancesViewModel.kt
app/src/main/java/com/hover/stax/channels/ChannelsViewModel.kt
app/src/main/java/com/hover/stax/database/DatabaseRepo.kt
app/src/main/java/com/hover/stax/requests/NewRequestFragment.kt
app/src/main/java/com/hover/stax/settings/SettingsFragment.kt
app/src/main/java/com/hover/stax/transfers/TransferFragment.kt
app/src/main/res/layout/balance_item.xml

Default account updated successfully from settings.

181534590 update default account

---

.idea/misc.xml
app/build.gradle
app/src/main/java/com/hover/stax/accounts/AccountDetailFragment.kt
app/src/main/java/com/hover/stax/financialTips/FinancialTipsFragment.kt
app/src/main/java/com/hover/stax/home/HomeFragment.kt
app/src/main/java/com/hover/stax/home/NavigationInterface.kt
app/src/main/java/com/hover/stax/home/StaxNavigation.kt
app/src/main/java/com/hover/stax/onboarding/OnBoardingActivity.kt
app/src/main/java/com/hover/stax/onboarding/interactiveVariant/InteractiveOnboardingVariant.kt
app/src/main/java/com/hover/stax/onboarding/interactiveVariant/InteractiveTutorialFragment.kt
app/src/main/java/com/hover/stax/onboarding/interactiveVariant/NonInteractiveTutorialFragment.kt
app/src/main/java/com/hover/stax/onboarding/signInVariant/SignInVariantFragment.kt
app/src/main/java/com/hover/stax/onboarding/welcome/WelcomeFragment.kt
app/src/main/java/com/hover/stax/requests/NewRequestFragment.kt
app/src/main/java/com/hover/stax/transfers/AbstractFormFragment.kt
app/src/main/java/com/hover/stax/transfers/TransferFragment.kt
app/src/main/java/com/hover/stax/utils/NavUtil.kt
app/src/main/java/com/hover/stax/utils/UIHelper.kt
app/src/main/java/com/hover/stax/utils/Utils.kt
app/src/main/res/navigation/home_navigation.xml
app/src/main/res/navigation/onboarding_navigation.xml
build.gradle

- adds safeargs plugin
- navigation for problematic fragments is through fragment directions. 
- added helper function to always validate the current destination before navigating.

181712053 nav fix

---

app/src/main/java/com/hover/stax/login/AbstractGoogleAuthActivity.kt
app/src/main/java/com/hover/stax/login/LoginViewModel.kt
app/src/main/res/values/strings.xml

- minor fixes to Google login flow. 
- fixes toast showing up when running txns

Google Login fixes

---

.idea/misc.xml
app/src/main/java/com/hover/stax/channels/AddChannelsFragment.kt
app/src/main/java/com/hover/stax/views/RequestServiceDialog.kt
app/src/main/res/layout/dialog_layout_button_area.xml
app/src/main/res/layout/dialog_layout_header_area.xml
app/src/main/res/layout/fragment_add_channels.xml
app/src/main/res/layout/request_for_service.xml
app/src/main/res/layout/stax_dialog.xml
app/src/main/res/values/logging_strings.xml
app/src/main/res/values/strings.xml

- Add click to "inform us here" to request a  new service.
- Created RequestService dialog.
- Send requested service to admin via Analytics. The goal is to receive this info primarily on Amplitude, but it's okay to send the same event to others as well.

180668840 request to add services

---

.idea/misc.xml
app/build.gradle
app/src/main/java/com/hover/stax/channels/ImportChannelsWorker.kt
app/src/main/java/com/hover/stax/database/DatabaseRepo.kt
app/src/main/java/com/hover/stax/financialTips/FinancialTipsFragment.kt
app/src/main/java/com/hover/stax/transactions/TransactionDao.kt
app/src/main/java/com/hover/stax/transactions/TransactionDetailsViewModel.kt
app/src/main/res/drawable/ic_baseline_open_in_new_16.xml
app/src/main/res/layout/no_account_empty_state.xml

- transaction updates from flow
- minor UI update on requesting services
- cleanup

minor update

---

.idea/gradle.xml
app/build.gradle
app/src/main/java/com/hover/stax/channels/AddChannelsFragment.kt
app/src/main/res/values/strings.xml

updates info text

---

app/build.gradle
app/src/main/java/com/hover/stax/home/HomeFragment.kt
app/src/main/java/com/hover/stax/transactions/TransactionDetailsFragment.kt
app/src/main/res/values/strings.xml

181512365 airtime bonus

---

app/src/main/java/com/hover/stax/permissions/ManagePermissionsFragment.kt

Accessibility intent needed a: Intent.FLAG_ACTIVITY_CLEAR_TOP, instead of FLAG_ACTIVITY_NO_HISTORY

182237080-accessibility-toggle-bug-fix

---

.idea/misc.xml
app/build.gradle
app/src/main/java/com/hover/stax/database/Modules.kt
app/src/main/java/com/hover/stax/database/ParserRepo.kt
app/src/main/java/com/hover/stax/transactions/StaxTransaction.java
app/src/main/java/com/hover/stax/transactions/TransactionDetailsFragment.kt
app/src/main/java/com/hover/stax/transactions/TransactionDetailsViewModel.kt
app/src/main/java/com/hover/stax/transactions/TransactionStatus.kt
app/src/main/res/values/strings.xml

Requires pulling the latest `sdk stax` version.

181796566 bug fix waiting for sms

---

app/schemas/com.hover.stax.database.AppDatabase/41.json
app/src/main/java/com/hover/stax/addChannels/ChannelsViewModel.kt
app/src/main/java/com/hover/stax/channels/Channel.java
app/src/main/java/com/hover/stax/channels/ChannelDao.kt
app/src/main/java/com/hover/stax/database/AppDatabase.kt
app/src/main/java/com/hover/stax/ussd_library/LibraryChannelsAdapter.kt
app/src/main/java/com/hover/stax/ussd_library/LibraryFragment.kt
app/src/main/res/drawable/favorite_empty.xml
app/src/main/res/drawable/favorite_filled.xml
app/src/main/res/layout/library_list_item.xml

Based on the story:
Why
Users don't want to have to hunt thru a list or type a search query every time they need to dial a code.
What
Add a one-tap favourite button. To the left of each entry in the USSD library show an empty star. When tapped the channel is favourited, which fills in the star in blue. Favourited channels always show at the top of the list if they match the filter parameters

181584835 fav ussd

---

app/src/main/java/com/hover/stax/merchants/MerchantFragment.kt
app/src/main/java/com/hover/stax/paybill/PaybillFragment.kt
app/src/main/java/com/hover/stax/paybill/PaybillViewModel.kt
app/src/main/java/com/hover/stax/transfers/TransferFragment.kt
app/src/main/res/drawable/icon_bg_circle.xml
app/src/main/res/layout/paybill_card_save.xml
app/src/main/res/navigation/home_navigation.xml
build.gradle

- Adds missing deep links. Tested all and ensured they are working. 
- Updates save paybill card design.
- Adds missing flow to add new account on paybill and merchant fragments when no accounts are added. 
- Fixes banner message display on buy airtime screen.

Merge bugfixes

---

app/build.gradle
app/src/main/java/com/hover/stax/balances/BalanceAdapter.kt
app/src/main/java/com/hover/stax/balances/BalancesFragment.kt
app/src/main/java/com/hover/stax/balances/BalancesViewModel.kt
app/src/main/java/com/hover/stax/database/Modules.kt

- this implementation is only temporary and will be overwritten with the new home screen changes.

temporary bugfix for balances

---

app/src/main/java/com/hover/stax/accounts/AccountsViewModel.kt
app/src/main/java/com/hover/stax/addChannels/AddChannelsFragment.kt
app/src/main/java/com/hover/stax/requests/RequestSenderInterface.kt
app/src/main/res/values/strings.xml

- Fixes share request bug.
- Fixes crash on empty channels on Add Accounts flow. 
- Fixes changing default account crash.

fixes recurrent bugs

---

app/src/main/java/com/hover/stax/addChannels/AddChannelsFragment.kt
app/src/main/java/com/hover/stax/financialTips/FinancialTipsFragment.kt
app/src/main/java/com/hover/stax/requests/NewRequestViewModel.kt
app/src/main/java/com/hover/stax/requests/RequestDetailViewModel.kt
app/src/main/java/com/hover/stax/transfers/TransferViewModel.kt

- fixes issues with back navigation from system button

fixes financial tips back navigation

---

app/src/main/res/values/strings.xml

typo fix for wont

---

app/src/main/java/com/hover/stax/transactionDetails/TransactionDetailsFragment.kt
app/src/main/java/com/hover/stax/transactions/TransactionUiDelegate.kt
app/src/main/res/layout/fragment_transaction.xml
app/src/main/res/navigation/home_navigation.xml

- Fixes reason on transaction history showing with HTML tags. 
- Back navigation from transaction details navigates to history. Bounties still behave as usual since bounty transactions don't show up in history.

182818957 nav to history from detail

---

app/src/main/java/com/hover/stax/data/remote/StaxApi.kt
app/src/main/java/com/hover/stax/presentation/home/components/VerticalImageTextView.kt
app/src/main/java/com/hover/stax/presentation/rewards/RewardsScreen.kt
app/src/main/java/com/hover/stax/presentation/rewards/components/ActionItem.kt
app/src/main/java/com/hover/stax/presentation/rewards/components/PointsDistributionDetail.kt
app/src/main/java/com/hover/stax/presentation/rewards/components/PointsHeader.kt
app/src/main/java/com/hover/stax/presentation/rewards/components/RecentPointsHeader.kt
app/src/main/java/com/hover/stax/presentation/rewards/components/RewardItem.kt
app/src/main/java/com/hover/stax/presentation/rewards/components/RewardsHistoryItem.kt
app/src/main/java/com/hover/stax/ui/theme/Color.kt
app/src/main/res/values/strings.xml

This PR brings over the rewards UI.

182487314 rewards screen

---

app/src/main/java/com/hover/stax/accounts/AccountDetailFragment.kt
app/src/main/java/com/hover/stax/accounts/AccountDetailViewModel.kt
app/src/main/java/com/hover/stax/data/local/channels/ChannelDao.kt
app/src/main/java/com/hover/stax/data/local/channels/ChannelRepo.kt
app/src/main/java/com/hover/stax/data/repository/AccountRepositoryImpl.kt
app/src/main/java/com/hover/stax/transactionDetails/TransactionDetailsFragment.kt
app/src/main/java/com/hover/stax/transactions/TransactionHistoryAdapter.kt
app/src/main/java/com/hover/stax/transactions/TransactionHistoryFragment.kt
app/src/main/java/com/hover/stax/transactions/TransactionHistoryViewModel.kt
app/src/main/java/com/hover/stax/transactions/TransactionUiDelegate.kt
app/src/main/res/values-om/strings.xml
app/src/main/res/values-so/strings.xml
app/src/main/res/values/strings.xml

Added institution-type information to the transaction history so that where it previously says
- Waiting for confirmation now becomes "Waiting for {type} confirmation".
- New Balance now becomes "New {type} Balance".

added institution name to the transaction history item

---

app/build.gradle
app/src/main/java/com/hover/stax/presentation/home/components/TopBar.kt
app/src/main/res/values/strings.xml

- Updated the form link url for money mappers.
- Hidden rewards icon from topbar.

Merge version 1.13.3

---

app/src/debug/res/values/strings.xml

changed endpoint

---

app/schemas/com.hover.stax.database.AppDatabase/45.json
app/src/main/java/com/hover/stax/addChannels/AddChannelsFragment.kt
app/src/main/java/com/hover/stax/database/AppDatabase.kt
app/src/main/java/com/hover/stax/ussd_library/LibraryFragment.kt

Fixes 2 issues found by John https://www.pivotaltracker.com/story/show/183284652
the change to make the institution types non-null caused issues because you tried to add columns that already existed. There are SQL commands to change a column from nullable to not, but I think in this case they are unnecessary because you've already set a default value for the column. There should be no way to make the column null if it has a default (and we aren't sending null from our server). Let me know if you think there is an issue with this approach.

183284652 crash fixes

---

app/src/main/java/com/hover/stax/presentation/welcome/WelcomeFragment.kt
app/src/main/java/com/hover/stax/presentation/welcome/WelcomeScreen.kt

- Added a boolean to either show or hide the explore button.
- Some minor refactoring
https://user-images.githubusercontent.com/21104847/194510826-4baf318a-d4e1-47dd-a8d7-075db58b4b4e.mp4
.

complete task

---

app/src/main/java/com/hover/stax/settings/SettingsFragment.kt
app/src/main/res/layout/app_info_items.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/settings_app_details_card.xml
app/src/main/res/values/strings.xml

- Added App info segment.
- Made copiable items show or disappear when clicked;
https://user-images.githubusercontent.com/21104847/197636754-b0bc0e76-8f25-4163-b7f7-495a6730b048.mp4

added appInfo segment with intuitive visibility logic

---

app/src/main/java/com/hover/stax/settings/SettingsFragment.kt
app/src/main/res/drawable/ic_copy_grey.xml
app/src/main/res/layout/app_info_items.xml
app/src/main/res/layout/settings_account_card.xml
app/src/main/res/layout/settings_app_details_card.xml
app/src/main/res/layout/settings_card_language.xml
app/src/main/res/layout/settings_card_learn.xml
app/src/main/res/layout/settings_card_permissions.xml

Although I intend to update it to compose in the future, this improvement follows the convention in XML.
Here's an attached video describing the changes.
The present experience
https://user-images.githubusercontent.com/21104847/198086543-c0ff4853-982b-47a1-b025-6d7d96dfb23a.mp4
The new experience
https://user-images.githubusercontent.com/21104847/198086585-bc1aa72c-3363-45ad-8c32-3bb805d88b23.mp4

183640856 Improve haptic feedback on items on the settings screen

---

app/src/main/java/com/hover/stax/RoutingActivity.kt
app/src/main/java/com/hover/stax/login/AbstractGoogleAuthActivity.kt
app/src/main/res/values/logging_strings.xml
app/src/main/res/xml/remote_config_default.xml

- There was a wrong conditional statement, "If build is debug, then check for update", preventing the force update -  I've fixed this.
- Previous logic gives a grace period of 3 days; now we can enforce an update.
**How to test**
Because the google play library attempts to download the version online, testing could happen on production by increasing the `force_update_app_version` and confirming it works on the device.

Alternative solution to force update 

---

app/build.gradle
app/src/main/java/com/hover/stax/di/Modules.kt

Introducing Chucker makes it easy to debug network calls, but on debug builds only

Introduce Chucker to debug network calls on debug builds

---

app/build.gradle
app/src/main/java/com/hover/stax/domain/model/Account.kt
app/src/main/java/com/hover/stax/hover/AbstractHoverCallerActivity.kt
app/src/main/java/com/hover/stax/transfers/TransferViewModel.kt

Fix account name input extra case, which should fix many "service integration is broken" issues.

Release 1.17.3

---

app/src/main/java/com/hover/stax/transfers/NonStandardVariableAdapter.kt
app/src/main/java/com/hover/stax/transfers/TransferFragment.kt
app/src/main/res/layout/fragment_transfer.xml
app/src/main/res/layout/transfer_card_edit.xml

I was not able to figure out the root cause of this issue. To fix it, adds the edit boxes in fragment manually, an adapter isn't really necessary anyway. I did try to change it from a recycler view to list view, but the problem was the same.
[Finishes #183687048]

Fix non standard variables not able to get focus

---

app/src/main/java/com/hover/stax/domain/use_case/sims/ListSimsUseCase.kt
app/src/main/java/com/hover/stax/presentation/sims/components/SimItem.kt

Refactored how the bonus is retrieved on SimItem.
Considering that the bonus is default zero on HoverAction, I updated the conditional logic.

183789969 sim screen hotfix

---

app/src/main/java/com/hover/stax/addChannels/AddChannelsFragment.kt
app/src/main/java/com/hover/stax/addChannels/ChannelsViewModel.kt

This is a simple fix - reset the channel list when setting up the search component. The AddChannelsFragment still retains the selected country but resets the channels

183798671 Reset Channel List 

---

app/src/main/java/com/hover/stax/domain/use_case/sims/ListSimsUseCase.kt
app/src/main/java/com/hover/stax/presentation/sims/components/SimItem.kt

Basically makes the list nullable, and use's the firstOrNull

Make Sim Actions nullable

---

app/src/main/java/com/hover/stax/transactionDetails/TransactionDetailsFragment.kt
app/src/main/java/com/hover/stax/utils/Utils.kt

Should really make the db field a string, but that may have wider ramifications, this is easy.

Add a method to re-format the amount to remove decimals if unneccessary

---

gradle/libs.versions.toml

* Updates the hover sdk version

Prepare Release 1.18.3

---

.github/workflows/qa-release.yml
gradle/libs.versions.toml

* Updates the hover sdk version

Release 1.18.3

---

app/build.gradle.kts

Downgrading target version to 32

Downgrade to 32

---

gradle/libs.versions.toml

I did a brief lib update and tested it doesn't break Stax.

update appsflyer library

---

app/src/main/java/com/hover/stax/permissions/PermissionsFragment.kt
app/src/main/res/drawable/ic_chevron_down.xml
app/src/main/res/layout/stax_permission_dialog.xml
app/src/main/res/values/strings.xml

Updates text on the settings page to the same.

Update Accessibility request dialog to add info required by Google

---

app/src/main/java/com/hover/stax/presentation/home/HomeFragment.kt
app/src/main/java/com/hover/stax/presentation/home/HomeScreen.kt
app/src/main/java/com/hover/stax/presentation/home/HomeState.kt
app/src/main/java/com/hover/stax/presentation/home/HomeViewModel.kt

I had to move from using StateFlow to a MutableLiveData since the composable doesn't recompose whenever state flow is updated. Not sure if this has anything to do with the nested UI, but it looks like the UI is destroyed and recreated when the user manually navigates to home screen using the home tab option, and doesn't change when the view was in the backstack - someone pressing back button 
Finishes #183857624

183857624 Update Balance on Home and Sim Screens

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/hover/stax/RoutingActivity.kt
app/src/main/java/com/hover/stax/ktor/EnvironmentProvider.kt

Straightforward implementation to deep-link to the share page.
I need help to test it, as it requires a debug SHA to test off production.

183981975 deeplink settings page

---

README.md

This PR updates the README to reflect the current grade setup and get the project running for the first time.

Update README.md Project Setup Instructions

---

app/src/main/java/com/hover/stax/hover/TransactionReceiver.kt
gradle/libs.versions.toml

Update SDK which has select by text parsing fixes as well
Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #969 #962 probably a bunch of others that involve balance checks on multi-account USSD, especially KCB and COOP🦕

Using regex from config to parse account list if available

---

app/src/test/java/com/hover/stax/schedules/ScheduleDetailViewModelTest.kt
app/src/test/java/com/hover/stax/utils/MainDispatcherRule.kt
gradle/libs.versions.toml

This PR Adds Unit tests for the ScheduleDetailsViewModel class.

ScheduleViewModel Unit Test
